/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mycompany.contacto_3xtrat3rr3str3d.ui;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.text.DefaultStyledDocument;
/**
 *
 * @author mauricio
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName());

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }
    
    class NodoArchivo
    {
        File archivo;
        public NodoArchivo(File archivo)
        { 
            this.archivo = archivo; 
        }
        @Override
        public String toString()
        { 
            return archivo.getName(); 
        }
    }
    
    private void llenarArbol(File carpeta, DefaultMutableTreeNode nodoPadre)
    {
        File[] archivos = carpeta.listFiles();
        if (archivos != null)
        {
            for (File archivo : archivos)
            {
                DefaultMutableTreeNode nodoHijo = new DefaultMutableTreeNode(new NodoArchivo(archivo));
                nodoPadre.add(nodoHijo);
                if (archivo.isDirectory())
                {
                    llenarArbol(archivo, nodoHijo);
                }
            }
        }
    }
    
    private void abrirArchivoEnPestaña(File archivo)
    {
        String nombreArchivo = archivo.getName();
        for (int i = 0; i < panelPestañas.getTabCount(); i++)
        {
            if (panelPestañas.getTitleAt(i).equals(nombreArchivo))
            {
                panelPestañas.setSelectedIndex(i);
                return;
            }
        }
        try
        {
            String contenido = new String(Files.readAllBytes(archivo.toPath()));
            ColoreadoSintaxis doc = new ColoreadoSintaxis();
            JTextPane editor = new JTextPane(doc);
            editor.setFont(new java.awt.Font("Monospaced", java.awt.Font.PLAIN, 14));
            editor.setText(contenido);
            editor.putClientProperty("archivoFisico", archivo);
            JScrollPane scroll = new JScrollPane(editor);
            panelPestañas.addTab(archivo.getName(), scroll);
            panelPestañas.setSelectedComponent(scroll);
        }
        catch (IOException e)
        {
            JOptionPane.showMessageDialog(this, "Error al leer el archivo: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitHorizontal = new javax.swing.JSplitPane();
        splitVertical = new javax.swing.JSplitPane();
        panelPestañas = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        treeArchivos = new javax.swing.JTree();
        jScrollPane2 = new javax.swing.JScrollPane();
        consolaSalida = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        itemAbrirProyecto = new javax.swing.JMenuItem();
        itemGuardar = new javax.swing.JMenuItem();
        menuEjecutar = new javax.swing.JMenu();
        itemAnalizar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("IDE Contacto 3xtrat3rr3str3D");

        splitHorizontal.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        splitVertical.setRightComponent(panelPestañas);

        treeArchivos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                treeArchivosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(treeArchivos);

        splitVertical.setLeftComponent(jScrollPane1);

        splitHorizontal.setLeftComponent(splitVertical);

        consolaSalida.setColumns(20);
        consolaSalida.setRows(5);
        jScrollPane2.setViewportView(consolaSalida);

        splitHorizontal.setRightComponent(jScrollPane2);

        menuArchivo.setText("Archivo");

        itemAbrirProyecto.setText("Abrir Proyecto");
        itemAbrirProyecto.addActionListener(this::itemAbrirProyectoActionPerformed);
        menuArchivo.add(itemAbrirProyecto);

        itemGuardar.setText("Guardar");
        menuArchivo.add(itemGuardar);

        jMenuBar1.add(menuArchivo);

        menuEjecutar.setText("Ejecutar");

        itemAnalizar.setText("Analizar Código");
        menuEjecutar.add(itemAnalizar);

        jMenuBar1.add(menuEjecutar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(splitHorizontal, javax.swing.GroupLayout.DEFAULT_SIZE, 1122, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(splitHorizontal, javax.swing.GroupLayout.DEFAULT_SIZE, 633, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void itemAbrirProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAbrirProyectoActionPerformed
        JFileChooser buscador = new JFileChooser();
        buscador.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int seleccion = buscador.showOpenDialog(this);
        if (seleccion == JFileChooser.APPROVE_OPTION)
        {
            File carpetaSeleccionada = buscador.getSelectedFile();
            DefaultMutableTreeNode nodoRaiz = new DefaultMutableTreeNode(new NodoArchivo(carpetaSeleccionada));
            llenarArbol(carpetaSeleccionada, nodoRaiz);
            DefaultTreeModel modeloArbol = new DefaultTreeModel(nodoRaiz);
            treeArchivos.setModel(modeloArbol);
        }
    }//GEN-LAST:event_itemAbrirProyectoActionPerformed

    private void treeArchivosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_treeArchivosMouseClicked
        if (evt.getClickCount() == 2)
        {
            DefaultMutableTreeNode nodoSeleccionado = (DefaultMutableTreeNode) treeArchivos.getLastSelectedPathComponent();
            if (nodoSeleccionado != null && nodoSeleccionado.getUserObject() instanceof NodoArchivo)
            {
                File archivo = ((NodoArchivo) nodoSeleccionado.getUserObject()).archivo;
                if (archivo.isFile())
                {
                    abrirArchivoEnPestaña(archivo);
                }
            }
        }
    }//GEN-LAST:event_treeArchivosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea consolaSalida;
    private javax.swing.JMenuItem itemAbrirProyecto;
    private javax.swing.JMenuItem itemAnalizar;
    private javax.swing.JMenuItem itemGuardar;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenu menuEjecutar;
    private javax.swing.JTabbedPane panelPestañas;
    private javax.swing.JSplitPane splitHorizontal;
    private javax.swing.JSplitPane splitVertical;
    private javax.swing.JTree treeArchivos;
    // End of variables declaration//GEN-END:variables
}
