/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mycompany.contacto_3xtrat3rr3str3d.ui;
import java.awt.Component;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.text.DefaultStyledDocument;
import mycompany.contacto_3xtrat3rr3str3d.PigLatinLexer;
import mycompany.contacto_3xtrat3rr3str3d.PigLatinParser;
import mycompany.contacto_3xtrat3rr3str3d.YLexer;
import mycompany.contacto_3xtrat3rr3str3d.YParser;
import mycompany.contacto_3xtrat3rr3str3d.ZetarianoLexer;
import mycompany.contacto_3xtrat3rr3str3d.ZetarianoParser;
import org.antlr.v4.runtime.CharStream;
import org.antlr.v4.runtime.CharStreams;
import org.antlr.v4.runtime.CommonTokenStream;
import org.antlr.v4.runtime.tree.ParseTree;
/**
 *
 * @author mauricio
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName());
    private File carpetaProyectoActual;
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }
    
    class NodoArchivo
    {
        File archivo;
        public NodoArchivo(File archivo)
        { 
            this.archivo = archivo; 
        }
        @Override
        public String toString()
        { 
            return archivo.getName(); 
        }
    }
    
    private void llenarArbol(File carpeta, DefaultMutableTreeNode nodoPadre)
    {
        File[] archivos = carpeta.listFiles();
        if (archivos != null)
        {
            for (File archivo : archivos)
            {
                DefaultMutableTreeNode nodoHijo = new DefaultMutableTreeNode(new NodoArchivo(archivo));
                nodoPadre.add(nodoHijo);
                if (archivo.isDirectory())
                {
                    llenarArbol(archivo, nodoHijo);
                }
            }
        }
    }
    
    private void abrirArchivoEnPestaña(File archivo)
    {
        String nombreArchivo = archivo.getName();
        for (int i = 0; i < panelPestañas.getTabCount(); i++)
        {
            if (panelPestañas.getTitleAt(i).equals(nombreArchivo))
            {
                panelPestañas.setSelectedIndex(i);
                return;
            }
        }
        try
        {
            String contenido = new String(Files.readAllBytes(archivo.toPath()));
            ColoreadoSintaxis doc = new ColoreadoSintaxis();
            JTextPane editor = new JTextPane(doc);
            editor.setFont(new java.awt.Font("Monospaced", java.awt.Font.PLAIN, 14));
            editor.setText(contenido);
            editor.putClientProperty("archivoFisico", archivo);
            JScrollPane scroll = new JScrollPane(editor);
            NumeroLinea numeros = new NumeroLinea(editor);
            scroll.setRowHeaderView(numeros);
            panelPestañas.addTab(archivo.getName(), scroll);
            panelPestañas.setSelectedComponent(scroll);
        }
        catch (IOException e)
        {
            JOptionPane.showMessageDialog(this, "Error al leer el archivo: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitHorizontal = new javax.swing.JSplitPane();
        splitVertical = new javax.swing.JSplitPane();
        panelPestañas = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        treeArchivos = new javax.swing.JTree();
        jScrollPane2 = new javax.swing.JScrollPane();
        consolaSalida = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        itemNuevoArchivo = new javax.swing.JMenuItem();
        itemAbrirProyecto = new javax.swing.JMenuItem();
        itemGuardar = new javax.swing.JMenuItem();
        itemCerrarArchivo = new javax.swing.JMenuItem();
        menuEjecutar = new javax.swing.JMenu();
        itemAnalizar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("IDE Contacto 3xtrat3rr3str3D");

        splitHorizontal.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        splitVertical.setRightComponent(panelPestañas);

        treeArchivos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                treeArchivosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(treeArchivos);

        splitVertical.setLeftComponent(jScrollPane1);

        splitHorizontal.setLeftComponent(splitVertical);

        consolaSalida.setEditable(false);
        consolaSalida.setColumns(20);
        consolaSalida.setRows(5);
        jScrollPane2.setViewportView(consolaSalida);

        splitHorizontal.setRightComponent(jScrollPane2);

        menuArchivo.setText("Archivo");

        itemNuevoArchivo.setText("Nuevo Archivo");
        itemNuevoArchivo.addActionListener(this::itemNuevoArchivoActionPerformed);
        menuArchivo.add(itemNuevoArchivo);

        itemAbrirProyecto.setText("Abrir Proyecto");
        itemAbrirProyecto.addActionListener(this::itemAbrirProyectoActionPerformed);
        menuArchivo.add(itemAbrirProyecto);

        itemGuardar.setText("Guardar");
        itemGuardar.addActionListener(this::itemGuardarActionPerformed);
        menuArchivo.add(itemGuardar);

        itemCerrarArchivo.setText("Cerrar Pestaña Actual");
        itemCerrarArchivo.addActionListener(this::itemCerrarArchivoActionPerformed);
        menuArchivo.add(itemCerrarArchivo);

        jMenuBar1.add(menuArchivo);

        menuEjecutar.setText("Ejecutar");

        itemAnalizar.setText("Analizar Código");
        itemAnalizar.addActionListener(this::itemAnalizarActionPerformed);
        menuEjecutar.add(itemAnalizar);

        jMenuBar1.add(menuEjecutar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(splitHorizontal, javax.swing.GroupLayout.DEFAULT_SIZE, 1122, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(splitHorizontal, javax.swing.GroupLayout.DEFAULT_SIZE, 633, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void itemAbrirProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAbrirProyectoActionPerformed
        JFileChooser buscador = new JFileChooser();
        buscador.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int seleccion = buscador.showOpenDialog(this);
        if (seleccion == JFileChooser.APPROVE_OPTION)
        {
            File carpetaSeleccionada = buscador.getSelectedFile();
            this.carpetaProyectoActual = carpetaSeleccionada;
            DefaultMutableTreeNode nodoRaiz = new DefaultMutableTreeNode(new NodoArchivo(carpetaSeleccionada));
            llenarArbol(carpetaSeleccionada, nodoRaiz);
            DefaultTreeModel modeloArbol = new DefaultTreeModel(nodoRaiz);
            treeArchivos.setModel(modeloArbol);
        }
    }//GEN-LAST:event_itemAbrirProyectoActionPerformed

    private void treeArchivosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_treeArchivosMouseClicked
        if (evt.getClickCount() == 2)
        {
            DefaultMutableTreeNode nodoSeleccionado = (DefaultMutableTreeNode) treeArchivos.getLastSelectedPathComponent();
            if (nodoSeleccionado != null && nodoSeleccionado.getUserObject() instanceof NodoArchivo)
            {
                File archivo = ((NodoArchivo) nodoSeleccionado.getUserObject()).archivo;
                if (archivo.isFile())
                {
                    abrirArchivoEnPestaña(archivo);
                }
            }
        }
    }//GEN-LAST:event_treeArchivosMouseClicked

    private void itemGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemGuardarActionPerformed
        Component tabActiva = panelPestañas.getSelectedComponent();
        if (tabActiva instanceof JScrollPane)
        {
            try
            {
                JScrollPane scroll = (JScrollPane) tabActiva;
                JTextPane editor = (JTextPane) scroll.getViewport().getView();
                File archivo = (File) editor.getClientProperty("archivoFisico");
                if (archivo != null)
                {
                    Files.write(archivo.toPath(), editor.getText().getBytes());
                    JOptionPane.showMessageDialog(this, "Archivo guardado correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                }
            }
            catch (IOException e)
            {
                JOptionPane.showMessageDialog(this, "Error al guardar: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else
        {
            JOptionPane.showMessageDialog(this, "No hay ningún archivo abierto.", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_itemGuardarActionPerformed

    private void itemNuevoArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemNuevoArchivoActionPerformed
        if (carpetaProyectoActual == null)
        {
            JOptionPane.showMessageDialog(this, "Primero debes abrir un proyecto/carpeta.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        String nombreArchivo = JOptionPane.showInputDialog(this, "Ingrese el nombre del archivo con extensión .z, .y, .pig:", "Nuevo Archivo", JOptionPane.QUESTION_MESSAGE);
        if (nombreArchivo != null && !nombreArchivo.trim().isEmpty())
        {
            if (nombreArchivo.endsWith(".z") || nombreArchivo.endsWith(".y") || nombreArchivo.endsWith(".pig")) {
                try
                {
                    File nuevoArchivo = new File(carpetaProyectoActual, nombreArchivo);
                    if (nuevoArchivo.createNewFile())
                    {
                        JOptionPane.showMessageDialog(this, "Archivo creado exitosamente.");
                        DefaultMutableTreeNode nodoRaiz = new DefaultMutableTreeNode(new NodoArchivo(carpetaProyectoActual));
                        llenarArbol(carpetaProyectoActual, nodoRaiz);
                        treeArchivos.setModel(new DefaultTreeModel(nodoRaiz));
                        abrirArchivoEnPestaña(nuevoArchivo);
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(this, "El archivo ya existe.", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                }
                catch (IOException e)
                {
                    JOptionPane.showMessageDialog(this, "Error al crear el archivo: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Extensión inválida. Debe ser .z, .y o .pig", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_itemNuevoArchivoActionPerformed

    private void itemCerrarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCerrarArchivoActionPerformed
        int indiceActivo = panelPestañas.getSelectedIndex();
        if (indiceActivo != -1)
        {
            panelPestañas.remove(indiceActivo);
        }
    }//GEN-LAST:event_itemCerrarArchivoActionPerformed

    private void itemAnalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAnalizarActionPerformed
        Component tabActivo = panelPestañas.getSelectedComponent();
        if (tabActivo instanceof JScrollPane)
        {
            try
            {
                JScrollPane scroll = (JScrollPane) tabActivo;
                JTextPane editor = (JTextPane) scroll.getViewport().getView();
                File archivo = (File) editor.getClientProperty("archivoFisico");
                String codigoTexto = editor.getText();
                if (archivo != null)
                {
                    String nombreArchivo = archivo.getName();
                    consolaSalida.setText(" INICIANDO ANÁLISIS \n");
                    consolaSalida.append("Archivo: " + nombreArchivo + "\n\n");
                    CharStream input = CharStreams.fromString(codigoTexto);
                    if (nombreArchivo.endsWith(".z"))
                    {
                        ZetarianoLexer lexer = new ZetarianoLexer(input);
                        CommonTokenStream tokens = new CommonTokenStream(lexer);
                        ZetarianoParser parser = new ZetarianoParser(tokens);
                        ControladorErrores controlador = new ControladorErrores(consolaSalida);
                        lexer.removeErrorListeners();
                        parser.removeErrorListeners();
                        lexer.addErrorListener(controlador);
                        parser.addErrorListener(controlador);
                        ParseTree tree = parser.programa();
                        if (!controlador.hayErrores)
                        {
                            consolaSalida.append("Análisis Zetariano completado con éxito.\n");
                            consolaSalida.append("AST: " + tree.toStringTree(parser) + "\n");
                        }
                        else
                        {
                            consolaSalida.append("Se encontraron errores en el código Zetariano. No se puede generar el AST.\n");
                        }
                    }
                    else if (nombreArchivo.endsWith(".y"))
                    {
                        YLexer lexer = new YLexer(input);
                        CommonTokenStream tokens = new CommonTokenStream(lexer);
                        YParser parser = new YParser(tokens);
                        ControladorErrores controlador = new ControladorErrores(consolaSalida);
                        lexer.removeErrorListeners();
                        parser.removeErrorListeners();
                        lexer.addErrorListener(controlador);
                        parser.addErrorListener(controlador);
                        ParseTree tree = parser.programa();
                        if (!controlador.hayErrores)
                        {
                            consolaSalida.append("Análisis Y? completado con éxito.\n");
                            consolaSalida.append("AST: " + tree.toStringTree(parser) + "\n");
                        }
                        else
                        {
                            consolaSalida.append("Se encontraron errores en el código Y?. No se puede generar el AST.\n");
                        }
                    }
                    else if (nombreArchivo.endsWith(".pig"))
                    {
                        PigLatinLexer lexer = new PigLatinLexer(input);
                        CommonTokenStream tokens = new CommonTokenStream(lexer);
                        PigLatinParser parser = new PigLatinParser(tokens);
                        ControladorErrores controlador = new ControladorErrores(consolaSalida);
                        lexer.removeErrorListeners();
                        parser.removeErrorListeners();
                        lexer.addErrorListener(controlador);
                        parser.addErrorListener(controlador);
                        ParseTree tree = parser.programa();
                        if (!controlador.hayErrores)
                        {
                            consolaSalida.append("Análisis Pig Latin completado con éxito.\n");
                            consolaSalida.append("AST: " + tree.toStringTree(parser) + "\n");
                        }
                        else
                        {
                            consolaSalida.append("Se encontraron errores en el código Pig Latin. No se puede generar el AST.\n");
                        }
                    }
                    else
                    {
                        consolaSalida.append("No se reconoce la extensión para el análisis.\n");
                    }
                    consolaSalida.append("\n");
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "El archivo no tiene una ruta establecida debes guardarlo primero.", "Aviso", JOptionPane.WARNING_MESSAGE);
                }
            }
            catch (Exception e)
            {
                consolaSalida.append("Error crítico durante el análisis: " + e.getMessage() + "\n");
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "No hay ningún archivo abierto para analizar.", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_itemAnalizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea consolaSalida;
    private javax.swing.JMenuItem itemAbrirProyecto;
    private javax.swing.JMenuItem itemAnalizar;
    private javax.swing.JMenuItem itemCerrarArchivo;
    private javax.swing.JMenuItem itemGuardar;
    private javax.swing.JMenuItem itemNuevoArchivo;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenu menuEjecutar;
    private javax.swing.JTabbedPane panelPestañas;
    private javax.swing.JSplitPane splitHorizontal;
    private javax.swing.JSplitPane splitVertical;
    private javax.swing.JTree treeArchivos;
    // End of variables declaration//GEN-END:variables
}
